In [1]:
import numpy as np

In [3]:
data = [1,2,3]
print(type(data))
# ndarray 변환하는 함수 : array(iterable)
arr = np.array(data)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
# list for 사용
data = [1,2,3]
result = [] # 결과를 저장할 빈 리스트 생성
for i in data:
    result.append(i*10)
    
print(result)


[10, 20, 30]


In [5]:
# ndarray for 사용 X
arr = np.array(data)
print(arr*10)

[10 20 30]


In [7]:
# list 인덱싱
data2d = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(data2d[1][1])

5


In [8]:
arr = np.array(data2d)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# arr[1][1]
arr[1,1] # [행, 열] 형태로 접근 가능

5

In [12]:
print(arr)
print(arr[:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]


In [18]:
dir(arr) # arr : ndarray object
print(arr.dtype) # base address + (index * dtype)

int32


In [19]:
data2 = [
    [1,2],
    [3,4]
]
arr2 = np.array(data2)
print(arr2.shape) # (2,2)
print(arr2.ndim) # 2차원
print(arr2.dtype) # 데이터타입 

(2, 2)
2
int32


In [20]:
arr2 * 2

array([[2, 4],
       [6, 8]])

In [25]:
data1 = [1,2,3,4]
arr1 = np.array(data1)
arr1.shape, arr.ndim

((4,), 2)

In [24]:
data = [
    [1],
    [2],
    [3],
    [4]
]
arr = np.array(data)
arr.shape, arr.ndim

((4, 1), 2)

In [1]:
import numpy as np

In [3]:
a = np.arange(10000).reshape(100,100)
%timeit a[0,50]

56.7 ns ± 1.03 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [4]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [7]:
arr[:1]

array([0])

In [6]:
arr[0]

0

In [10]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# arr[[인덱스값, 인덱스값, 인덱스값,...]]
arr[[1,4,7]]

array([2, 5, 8])

In [12]:
arr = np.array(['A','B','C','D'])
arr

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [14]:
arr[[1,3]]

array(['B', 'D'], dtype='<U1')

In [17]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
arr[:2, 2:4]

array([[2, 3],
       [7, 8]])

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
arr[:2,[1,4]]

array([[1, 4],
       [6, 9]])

In [22]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
arr[[0,3],[0,4]]

array([ 0, 19])

In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [28]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [29]:
# list 사용 연산
a = [1,2,3]
b = [2,3,4]
a + b

[1, 2, 3, 2, 3, 4]

In [31]:
for i in range(len(a)):
    print(a[i]+b[i])

3
5
7


In [32]:
for i,j in zip(a,b):
    print(i+j)

3
5
7


In [33]:
# 요소별 연산
a = np.array([1,2,3])
b = np.array([2,3,4])
a+b


array([3, 5, 7])

In [34]:
a = np.array([1,2,3])
a + 2

array([3, 4, 5])

In [36]:
high = [92700,92400,92100,94300,92300]
low = [90000,91100,91700,92100,90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low
arr_diff

array([2700, 1300,  400, 2200, 1400])

In [38]:
a = [ 
[1,2,3],
[3,4,5]
]
arr = np.array(a)
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [41]:
arr.sum(), arr.sum(axis=0), arr.sum(axis=1)

(18, array([4, 6, 8]), array([ 6, 12]))

In [51]:
arr = np.array([1,2,3])
cond = ~((arr > 1) & (arr <3))
cond

array([ True, False,  True])

In [53]:
arr[~cond]

array([2])

In [57]:
arr = np.array([1,2,3])
cond = arr > 1
arr[cond] = 1
arr[~cond] = 0
arr

array([0, 1, 1])

In [64]:
# 
lge = np.array([93000,82400,99100,81000,72300])
lge <= 85000

array([False,  True, False,  True,  True])

In [63]:
(lge <= 85000).sum()

3

In [3]:
import numpy as np

In [4]:
x = np.linspace(0,10,3)
x

array([ 0.,  5., 10.])

In [5]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [6]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [8]:
c = np.hstack([a,b])
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
import pandas as pd

In [15]:
# from pandas import Series
data = [100,100,100]
s = pd.Series(
      data 
    # , name='kor'
    # , index=['홍길동','고길동','마이꼴']
)
s.name = 'kor'
s.index = ['홍길동','고길동','마이꼴']
print(s)

홍길동    100
고길동    100
마이꼴    100
Name: kor, dtype: int64


In [12]:
s.name = 'kor'
print(s)

0    10
1    20
2    30
Name: kor, dtype: int64


In [17]:
data = ['시가', '고가', 100]
s = pd.Series(data)
print(s)

0     시가
1     고가
2    100
dtype: object


In [19]:
type(s[2])

int

In [23]:
data = [1000,2000,3000]
s = pd.Series(data)
s.index = ['메로나','구구콘','하겐다즈']
print(s.index)
print(s.index.to_list())

Index(['메로나', '구구콘', '하겐다즈'], dtype='object')
['메로나', '구구콘', '하겐다즈']


In [27]:
data = [1000,2000,3000]
index = ['메로나','구구콘','하겐다즈']
s = pd.Series(data=data, index=index)
# s = pd.Series(data, index)
print(s.index)
values = s.values # 값 추출
print(values)

Index(['메로나', '구구콘', '하겐다즈'], dtype='object')
[1000 2000 3000]


In [32]:
data = [1000,2000,3000]
index = ['메로나','구구콘','하겐다즈']
# s = pd.Series(data=data, index=index)
# s = pd.Series(data, index=index)
s = pd.Series(data, index)
# s = pd.Series(index, data) # 순서가 중요하다. 틀린 방식이 아니다.

print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [34]:
print(s)
s2 = s.reindex(['메로나','비비빅','구구콘'])
print(s2)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64
메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [35]:
print(s2.fillna(0))

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [47]:
data = [1000,2000,3000]
idx = ['메로나','구구콘','하겐다즈']
s = pd.Series(data=data, index=idx)
print(s.iloc[0])
print(s.iloc[1])
print(s.iloc[2])

1000
2000
3000


In [50]:
data, index, s

([1000, 2000, 3000],
 ['메로나', '구구콘', '하겐다즈'],
 메로나     1000
 구구콘     2000
 하겐다즈    3000
 dtype: int64)

In [65]:
data = [1,2,3]
index = ['메로나','구구콘','하겐다즈']
s = pd.Series(data=data, index=index)
print(s.loc['메로나':'하겐다즈'])

메로나     1
구구콘     2
하겐다즈    3
dtype: int64


In [67]:
print(s.drop('메로나', inplace=True)) # inplace=False default
# print(s)

KeyError: "['메로나'] not found in axis"

In [69]:
철수 = pd.Series([10,20,30,20], index=['NAVER','SKT','KT','SAMSUNG'])
영희 = pd.Series([10,30,20], index=['SKT','KT','NAVER'])
print(철수)
print(영희)
철수+영희

NAVER      10
SKT        20
KT         30
SAMSUNG    20
dtype: int64
SKT      10
KT       30
NAVER    20
dtype: int64


KT         60.0
NAVER      30.0
SAMSUNG     NaN
SKT        30.0
dtype: float64