In [23]:
import numpy as np 
import pandas as pd 
import tensorflow
import warnings

from tensorflow import keras
from tensorflow.keras import layers

from tensorflow.keras.datasets import mnist
warnings.filterwarnings('ignore')

In [5]:
(train_data , train_labels),_ = mnist.load_data() 

In [7]:
train_data.shape

(60000, 28, 28)

In [9]:
train_images = train_data.reshape((60000,28*28))
train_images.shape

(60000, 784)

In [10]:
train_images[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [11]:
train_labels[0]

5

In [12]:
# 0-1사이 값으로 변환
train_images = train_images.astype('float32')/255
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [15]:
# np.random.randn/(len(train_images),784)[0]
np.random.random(((len(train_images),784)))[0]

array([5.53127241e-01, 2.72766018e-01, 8.55474009e-01, 3.51793122e-01,
       3.81994039e-02, 9.13023820e-01, 6.50824447e-01, 5.31749326e-01,
       3.82056862e-01, 5.48377821e-01, 7.77002502e-01, 8.47690572e-01,
       6.05170353e-02, 6.32575223e-01, 7.43014657e-01, 7.82285012e-02,
       1.82971299e-01, 4.09240102e-01, 1.01659103e-01, 3.36082196e-01,
       8.81733507e-01, 9.36145423e-01, 2.58597508e-01, 3.09221978e-01,
       1.50958959e-01, 1.67019355e-01, 1.56928958e-02, 8.95251043e-01,
       9.90603703e-02, 2.07748975e-02, 5.91505445e-02, 9.27822988e-03,
       5.32697070e-01, 5.20655998e-01, 3.29250303e-01, 8.63059461e-01,
       1.74553503e-02, 6.19370938e-01, 5.50720036e-01, 7.37045516e-01,
       5.48356192e-01, 8.48811557e-01, 9.18889270e-01, 1.41006350e-02,
       7.87034386e-01, 5.85019350e-01, 4.43465869e-02, 1.11928664e-01,
       4.71924200e-02, 9.68607273e-01, 8.29771441e-01, 7.90154804e-01,
       6.96570338e-01, 4.21496094e-02, 8.88996275e-01, 7.76371965e-01,
      

In [18]:
train_images_with_noise_channels = np.concatenate(
    [train_images,np.random.random((len(train_images),784))],axis=1
)
train_images_with_zeros_channels = np.concatenate(
    [train_images,np.zeros((len(train_images),784))],axis=1
)

In [21]:
train_images_with_noise_channels.shape,train_images_with_zeros_channels.shape

((60000, 1568), (60000, 1568))

In [36]:
def get_model():
    model = keras.Sequential([
        layers.Dense(512,activation = 'relu'),
        layers.Dense(10,activation = 'softmax')   
    ])
    model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])
    return model

In [37]:
model =get_model()
history_noise = model.fit(
    train_images_with_noise_channels,
    train_labels,
    epochs = 10,
    batch_size = 128,
    validation_split = 0.2
)

Epoch 1/10
375/375 [==============================] - 3s 8ms/step - loss: 0.6121 - accuracy: 0.8136 - val_loss: 0.3278 - val_accuracy: 0.8987
Epoch 2/10
375/375 [==============================] - 3s 7ms/step - loss: 0.2520 - accuracy: 0.9220 - val_loss: 0.2159 - val_accuracy: 0.9354
Epoch 3/10
375/375 [==============================] - 3s 7ms/step - loss: 0.1664 - accuracy: 0.9481 - val_loss: 0.1436 - val_accuracy: 0.9563
Epoch 4/10
375/375 [==============================] - 2s 7ms/step - loss: 0.1174 - accuracy: 0.9630 - val_loss: 0.1502 - val_accuracy: 0.9528
Epoch 5/10
375/375 [==============================] - 3s 7ms/step - loss: 0.0865 - accuracy: 0.9717 - val_loss: 0.1472 - val_accuracy: 0.9582
Epoch 6/10
375/375 [==============================] - 3s 7ms/step - loss: 0.0645 - accuracy: 0.9798 - val_loss: 0.1210 - val_accuracy: 0.9657
Epoch 7/10
375/375 [==============================] - 2s 7ms/step - loss: 0.0478 - accuracy: 0.9844 - val_loss: 0.1325 - val_accuracy: 0.9638
Epoch 